# This runs phpcs with the DrupalPractice coding standard from a standalone
# Docker container.
#
# This is not the recommended way; but would be useful if it is not possible to
# install 'squizlabs/php_codesniffer' and 'drupal/coder', which may be the case
# if you're adding Lando to an existing project.
services:
  phpcs-drupalpractice:
    type: compose
    services:
      image: 'mparker17/phpcs-drupalpractice'
      command: '/opt/coder/vendor/bin/phpcs --standard=DrupalPractice'
tooling:
  lint-practice-php:
    service: 'phpcs-drupalpractice'
    cmd:
      - '/opt/coder/vendor/bin/phpcs --standard=DrupalPractice'
